/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as IndexRouteImport } from './pages/index'
import { Route as TransactionsTransactionsRouteImport } from './pages/_transactions/transactions'
import { Route as PlansPlansRouteImport } from './pages/_plans/plans'
import { Route as PaymentsPaymentsRouteImport } from './pages/_payments/payments'
import { Route as MembersMembersRouteImport } from './pages/_members/members'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsTransactionsRoute =
  TransactionsTransactionsRouteImport.update({
    id: '/_transactions/transactions',
    path: '/transactions',
    getParentRoute: () => rootRouteImport,
  } as any)
const PlansPlansRoute = PlansPlansRouteImport.update({
  id: '/_plans/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsPaymentsRoute = PaymentsPaymentsRouteImport.update({
  id: '/_payments/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersMembersRoute = MembersMembersRouteImport.update({
  id: '/_members/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/members': typeof MembersMembersRoute
  '/payments': typeof PaymentsPaymentsRoute
  '/plans': typeof PlansPlansRoute
  '/transactions': typeof TransactionsTransactionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/members': typeof MembersMembersRoute
  '/payments': typeof PaymentsPaymentsRoute
  '/plans': typeof PlansPlansRoute
  '/transactions': typeof TransactionsTransactionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_members/members': typeof MembersMembersRoute
  '/_payments/payments': typeof PaymentsPaymentsRoute
  '/_plans/plans': typeof PlansPlansRoute
  '/_transactions/transactions': typeof TransactionsTransactionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/members' | '/payments' | '/plans' | '/transactions'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/members' | '/payments' | '/plans' | '/transactions'
  id:
    | '__root__'
    | '/'
    | '/_members/members'
    | '/_payments/payments'
    | '/_plans/plans'
    | '/_transactions/transactions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MembersMembersRoute: typeof MembersMembersRoute
  PaymentsPaymentsRoute: typeof PaymentsPaymentsRoute
  PlansPlansRoute: typeof PlansPlansRoute
  TransactionsTransactionsRoute: typeof TransactionsTransactionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_transactions/transactions': {
      id: '/_transactions/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsTransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_plans/plans': {
      id: '/_plans/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansPlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_payments/payments': {
      id: '/_payments/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_members/members': {
      id: '/_members/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MembersMembersRoute: MembersMembersRoute,
  PaymentsPaymentsRoute: PaymentsPaymentsRoute,
  PlansPlansRoute: PlansPlansRoute,
  TransactionsTransactionsRoute: TransactionsTransactionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
